baseURL: https://aafu.pages.dev/
languageCode: en-us
build:
  writeStats: true
params:
  title: Gene's samples
  author: Gene Hartsell
  description: Website title
  copyright: |+
    Copyright &copy; 2025 Gene Hartsell
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Documentation Samples"
    photo: profile.png
  social:
    title: Links
    list:
      - icon: fab fa-github
        url: "https://github.com/ghartsel"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: publication
    - item: education
    - item: project
  aboutme:
    title: About
    icon: fas fa-user
    description: |
      I've had the pleasure of writing complex developer and engineering documentation for great companies across a broad domain spectrum. These projects afforded me the opportunity to immerse myself in new technologies and engage with the latest documentation methodologies and tools.

      These are some of the types of documentation products I created:
      - &squarf; Web API, native API, and CLI references and user guides
      - &squarf; Tutorials and cookbooks
      - &squarf; Hardware reference guides and technical notes
      - &squarf; Software design and methodology specifications
      - &squarf; Various tool and technology user guides

      Where code examples are shown in the docs, I wrote and tested original code using the target programming or scripting language.

      Feel free to browse the publications and reach out if you have any questions: gene@docity.dev.
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - title
      - tool
      - summary
    types:
      - Serverless document database
      - Application Framework
      - Visualization API
      - Process Definition and Observability
      - Developer Guides
      - Hardware reference manuals
    list:
      - title: >-
          Fauna Docs
        tool: "(AsciiDoc / Antora) "
        summary:
          As the lone tech writer, I was responsible for the
          information architecture, content, CI/CD workflow, docs-as-code process, and Markdown and GitHub style guides.
          I implemented processes and tooling to ensure high documentation quality.
        url: "http://fdocsample.s3-website-us-west-1.amazonaws.com/fauna/current/index.html"
        type: Serverless document database
      - title: >-
          Splunk Application Framework Getting Started
        tool: "(Confluence wiki)"
        summary:
          My initial task was to provide reliable, clear, and accurate documentation for developers creating Splunk
          applications. This tutorial provided a quick introduction to building a Splunk application.
        url: "https://docs.splunk.com/Documentation/Splunk/7.3.3/Module/Environmentsetup"
        type: Application Framework
      - title: >-
          Splunk Application Framework Cookbook
        summary:
          The cookbook was at the heart of the documentation initiative to facilitate onboarding developers for creating Splunk
          applications. The cookbook provided a set of graduated, hands-on tutorials that gradually introduced developers
          to increasingly complex Splunk features.
        tool: "(Confluence wiki)"
        url: "http://docs.splunk.com/Documentation/Splunk/7.3.3/Module/Getthetutorialapp"
        type: Application Framework
      - title: >-
          Splunk REST API Reference
        summary:
          In volunteering to take responsibility for the REST API, I defined a developer-friendly API documentation format
          and replaced the existing automated documentation generation tool. OpenAPI was not an option.
        tool: "(Confluence wiki)"
        url: "https://docs.splunk.com/Documentation/Splunk/8.0.0/RESTREF/RESTprolog"
        type: Application Framework
      - title: >-
          OmniSci Vega User Guide
        summary:
          As one of several areas I documented for the GPU-based SQL database, I documented the OmniSci interface to the Vega
          data visualization library, integrating the Vega language with SQL. The documentation opens with an at-a-glance
          tutorial to provide context followed by a set of tutorials of increasing complexity that walk the developer through
          OmniSci and Vega features.
        tool: "(reStructuredText / Sphinx)"
        url: "https://docs.heavy.ai/apis-and-interfaces/vega"
        type: Visualization API
      - title: >-
          OmniSci Vega Native API Reference
        summary:
          The Vega API reference provides the syntactic details for using the Vega visualization language with OmniSci SQL.
        tool: "(reStructuredText / Sphinx)"
        url: "https://docs.heavy.ai/apis-and-interfaces/vega/vega-reference-overview"
        type: Visualization API
      - title: >-
          Process Definition
        summary:
          As the documentation manager leading an international team of tech writers, I defined
          the docs-as-code process, created and maintained documentation tools, and reviewed and edited the content of other writers,
          while continuing to produce original content such as these examples.
          This document and subsections describe the implementation of a process definition mechanism, based on Camunda, for automating event handling.
        tool: "(Markdown / Hugo)"
        url: "https://docs.opsramp.com/solutions/remediation-automation/process-automation/process-definitions/"
        type: Process Definition and Observability
      - title: >-
          Dashboard 2.0
        summary:
          This document and subsections show how to create dashboard visualizations, including Prometheus integration using PromQL.
        tool: "(Markdown / Hugo)"
        url: "https://docs.opsramp.com/platform-features/feature-guides/dashboards/dashboard20/"
        type: Process Definition and Observability
      - title: >-
          Configure Determined with Prometheus and Grafana
        summary:
          This document describes the setup and configuration to enable a Grafana dashboard to monitor Determined hardware
          and system metrics on a cloud cluster, such as AWS or Kubernetes. For the Determined AI distributed training
          product, I worked closely with the ML engineer to document how to integrate Prometheus and Grafana with
          Determined AI. I defined the topic structure, enforced documentation style guidelines, and verified content accuracy.
        tool: "(reStructuredText / Sphinx)"
        url: "https://dancing-taiyaki-b94c7f.netlify.app/integrations/prometheus/prometheus"
        type: Developer Guides
      - title: >-
          Juniper Networks WAN SDN Controller Developer Guide
        summary:
          As a consultant, I wrote the developer guide for the Juniper Networks NorthStar WAN SDN Controller to describe
          how to create applications that provided visibility and control over IP/MPLS and optical layer flows for WAN
          analysis and optimization, using the REST API.
        tool: ""
        url: "https://www.juniper.net/documentation/us/en/software/northstar6.2.6/api-ref/api-ref-northstar-devguide.html"
        type: Developer Guides
      - title: >-
          Ion Torrent Programming Guide with REST API Reference
        summary:
          As a consultant, I provided the first documentation for the Ion Torrent DNA sequencing machine. The documentation
          included a programming guide and REST API reference documentation. Pre-OpenAPI, I created a Python tool to traverse
          resources and autogenerate the REST API. I would later employ a similar mechanism at Splunk.
        tool: ""
        url: "https://ion-torrent-sdk.readthedocs.io/en/stable/"
        type: Developer Guides
      - title: >-
          Configuration and programming software (CAPS) tool for STR9 families
        summary:
          I worked with hardware engineers to document the UI for the STMicroelectronics STR9 configuration
          tool, assisting in debugging the tool. My previous experience writing board support packages, device drivers,
          and operating systems proved valuable in producing complete and accurate documentation.
        tool: "(FrameMaker)"
        url: "https://www.st.com/resource/en/user_manual/um0225-configuration-and-programming-software-caps-tool-for-str9-families-stmicroelectronics.pdf"
        type: Hardware reference manuals
      - title: >-
          Single-board computer with Integrated Data Acquisition and Configurable CPU
        summary:
          One of several hardware modules I documented, I provided a detailed reference for how to configure and use this
          single-board computer. For all documentation, I created an XSLT-based documentation tool that allowed WYSIWYG
          authoring by publishing OpenOffice ODF formatted files to HTML and PDF formats. I presented the tool and methodology,
          which sought alignment with the Darwin Information Typing Architecture (DITA), at STC Silicon Valley.
        tool: "(LibreOffice/XSLT)"
        url: "https://www.diamondsystems.com/files/binaries/Neptune%20User%20Manual.pdf"
        type: Hardware reference manuals
      - title: >-
          High Integration Single-board computer with Ethernet and Data Acquisition
        summary:
          Another hardware reference manual that describes how to configure and use an Ethernet and data acquisition SBC.
        tool: "(LibreOffice/XSLT)"
        url: "https://www.diamondsystems.com/files/binaries/Athena%20II%20User%20Manual.pdf"
        type: Hardware reference manuals
      - title: >-
          Board with dual CAN ports, carrier for wireless and GPS modules
        summary:
          Yet another hardware reference manual that describes how to configure a board featuring carrier and wireless GPS.
        tool: "(LibreOffice/XSLT)"
        url: "https://www.diamondsystems.com/files/binaries/JanusMMUserManual.pdf"
        type: Hardware reference manuals
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Static site generator in Go that supports reStructuredText
        url: "https://github.com/ghartsel/DoreStaticSiteGenerator"
        description: I implemented this static site generator in Go. It's inspired by the efficiency of Hugo and implements Sphinx paradigms to promote a documentation-centric authoring environment.
      - title: Sample output of the Go static site
        url: "https://ghartsel.github.io/demoyard/"
        description: This is an example of the output produced by the above Go static site generator.
      - title: WYSIWYG LibreOffice frontend for creating Markdown or reStructuredText content
        url: "https://github.com/ghartsel/RapidMarkup"
        description: This Python documentation tool uses an XSLT specification to convert ODF XML to Markdown or reStructuredText, enabling a writer-friendly, WYSIWYG authoring environment.
      - title: Sample microcontroller kernel developer guide
        url: "http://gxkernel.s3-website-us-west-1.amazonaws.com/index.html"
        description: This example demonstrates a 3-panel Hugo theme for showing examples in parallel with the documentation, which is popular for developer reference documentation. The content describes a kernel that I designed and implemented, which was written in C and assembly language.
      - title: Microcontroller kernel SDK documentation source
        url: "https://github.com/ghartsel/GX-Kernel"
        description: This is the Hugo static site source for the above 3-panel kernel documentation.
